inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - lib/**/*
    - bin/**/*
    - test/**/*
    - Gemfile
    - Rakefile
    - Thorfile
  Exclude:
    - example/**/*
    - test/data/*
  TargetRubyVersion: 2.2

Encoding:
 Enabled: false
RescueModifier:
 Enabled: false
HashSyntax:
 Enabled: false
SpaceInsideStringInterpolation:
  Enabled: false
DoubleNegation:
  Enabled: false
